name: send-letter-service-container-new
apiVersion: v2
description: A Helm chart for send-letter-service-container-new App
home: https://github.com/hmcts/send-letter-service-container-new
version: 0.0.4
maintainers:
  - name: HMCTS BSP Team
    email: bspteam@hmcts.net
dependencies:
  - name: java
    version: ~3.4.5
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
