apiVersion: v2
appVersion: "1.0"
description: A Helm chart for send-letter-service-container-new App
name: send-letter-service-container-new
home: https://github.com/hmcts/send-letter-service-container-new
version: 0.0.2
maintainers:
  - name: HMCTS rpe team
dependencies:
  - name: java
    version: 3.4.5
    repository: '@hmctspublic'
