apiVersion: v2
appVersion: "1.0"
description: A Helm chart for rpe-send-letter-service-container-new App
name: rpe-rpe-send-letter-service-container-new
home: https://github.com/hmcts/rpe-send-letter-service-container-new
version: 0.0.1
maintainers:
  - name: HMCTS rpe team
dependencies:
  - name: java
    version: 3.4.5
    repository: '@hmctspublic'
